### ISSUE TITLE
Error on mkdir with --strict mode

### ISSUE THREAD

**Issue by alexahdp** [louischatriot/nedb#172]
node_modules/nedb/node_modules/mkdirp/index.js:9
        mode = 0777 & (~process.umask());

SyntaxError: Octal literals are not allowed in strict mode.

**Comment by jedahan** [comment]
```shell
❯ cat nedb.js
var nedb = require('nedb')
var db = new nedb({ filename: 'test.db'})
```
```shell
❯ node --use-strict nedb.js
/Users/micro/code/bregalad/node_modules/nedb/node_modules/mkdirp/index.js:9
        mode = 0777 & (~process.umask());
               ^^^^

SyntaxError: Octal literals are not allowed in strict mode.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/micro/code/bregalad/node_modules/nedb/lib/storage.js:10:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

Its the same issue as https://github.com/substack/node-mkdirp/issues/88

So I updated nedb and things worked.

**Comment by louischatriot** [comment]
This has been fixed.
