### ISSUE TITLE
iojs test fail

### ISSUE THREAD

**Issue by rumkin** [louischatriot/nedb#259]
Test fails. Output:
```
1) Database Insert If a bulk insert violates a constraint, all changes are rolled back:
     SyntaxError: Unexpected end of input
      at Object.parse (native)
      at Object.deserialize (/apps/crypti/node_modules/nedb/lib/model.js:90:15)
      at /apps/crypti/node_modules/nedb/test/db.test.js:261:40
      at callback (/apps/crypti/node_modules/nedb/lib/executor.js:30:17)
      at Cursor.execFn (/apps/crypti/node_modules/nedb/lib/datastore.js:424:12)
      at Cursor._exec (/apps/crypti/node_modules/nedb/lib/cursor.js:172:17)
      at /apps/crypti/node_modules/nedb/lib/executor.js:40:13
      at Object.q.process (/apps/crypti/node_modules/nedb/node_modules/async/lib/async.js:731:21)
      at next (/apps/crypti/node_modules/nedb/node_modules/async/lib/async.js:728:27)
      at Immediate._onImmediate (/apps/crypti/node_modules/nedb/node_modules/async/lib/async.js:24:16)
      at processImmediate [as _immediateCallback] (timers.js:321:17)

  2) Model Modifying documents Throw an error if a modifier is used with a non-object argument:
     AssertionError: expected [Function] to throw an error
```
iojs 1.2.0, ubuntu 14.04, i686.

**Comment by louischatriot** [comment]
Seems like an issue with your machine, the piece of code that throws is part of node libs not nedb and this has not been reported by anyone else. Closing this for now, will reopen if someone else confirms this is a bug.
