### ISSUE TITLE
error: undefined is not a function on this.loadDatabase when using ` autoload: true`

### ISSUE THREAD

**Issue by angelxmoreno** [louischatriot/nedb#294]
my module: 
```
var Datastore = require('nedb')
var path = require('path');

module.exports = function(db_name){
    var file_name = path.join('../db', db_name+'.db');
    return Datastore({filename: file_name, autoload: true });
}
```

the error i get:
```
/Users/amoreno/Projects/node/helloworld/Hello World/node_modules/nedb/lib/datastore.js:66
  if (this.autoload) { this.loadDatabase(options.onload || function (err) {
                            ^
TypeError: undefined is not a function
    at Datastore (/Users/amoreno/Projects/node/helloworld/Hello World/node_modules/nedb/lib/datastore.js:66:29)
    at module.exports (/Users/amoreno/Projects/node/helloworld/Hello World/lib/db.js:7:12)
    at Object.<anonymous> (/Users/amoreno/Projects/node/helloworld/Hello World/server.js:3:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by szwacz** [comment]
How about `new Datastore`?

**Comment by louischatriot** [comment]
Yeah, you forgot the `new` :)

**Comment by angelxmoreno** [comment]
such fail. thanks guys. now to find where i copied and pasted from...
