### ISSUE TITLE
Error inserting documents - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by todojs** [louischatriot/nedb#326]
This is the gist:

https://gist.github.com/todojs/8f8a535ddfd2da507e88

It's very simple:

```
"use strict";
var Datastore = require('nedb'),
    db = new Datastore();

for (var n = 0; n < 1000000; n++){
    db.insert({n: n, now: new Date()});
}
```

The error is:

```
Datastore.prototype._insert = function (newDoc, cb) {
                                       ^

RangeError: Maximum call stack size exceeded
    at Datastore._insert (c:\Users\palmun\Documents\Dropbox\WebstormProjects\todojs\20151101-NeDB\node_modules\nedb\lib\datastore.js:283:40)
    at c:\Users\palmun\Documents\Dropbox\WebstormProjects\todojs\20151101-NeDB\node_modules\nedb\lib\executor.js:40:13
    at Object.q.process (c:\Users\palmun\Documents\Dropbox\WebstormProjects\todojs\20151101-NeDB\node_modules\nedb\node_modules\async\lib\async.js:731:21)
    at next (c:\Users\palmun\Documents\Dropbox\WebstormProjects\todojs\20151101-NeDB\node_modules\nedb\node_modules\async\lib\async.js:728:27)
    at c:\Users\palmun\Documents\Dropbox\WebstormProjects\todojs\20151101-NeDB\node_modules\nedb\node_modules\async\lib\async.js:24:16
    at callback (c:\Users\palmun\Documents\Dropbox\WebstormProjects\todojs\20151101-NeDB\node_modules\nedb\lib\executor.js:35:32)
    at Datastore._insert (c:\Users\palmun\Documents\Dropbox\WebstormProjects\todojs\20151101-NeDB\node_modules\nedb\lib\datastore.js:290:12)
    at c:\Users\palmun\Documents\Dropbox\WebstormProjects\todojs\20151101-NeDB\node_modules\nedb\lib\executor.js:40:13
    at Object.q.process (c:\Users\palmun\Documents\Dropbox\WebstormProjects\todojs\20151101-NeDB\node_modules\nedb\node_modules\async\lib\async.js:731:21)
    at next (c:\Users\palmun\Documents\Dropbox\WebstormProjects\todojs\20151101-NeDB\node_modules\nedb\node_modules\async\lib\async.js:728:27)
```

**Comment by louischatriot** [comment]
That's normal as you're not executing the inserts (no callback) so it's clogging the executor. You need to use node-style async programming for it to work as expected.

**Comment by todojs** [comment]
Thanks Louis,

I know perfectly the NodeJS and Javascript asynchronous programming patterns or the new ES6 generator pattern and we can serialized the calls, but you write in the documentation:

// Callback is optional

In the practice, the callback is not optional always (with few calls run perfectly withour callback).

Good job (NeDB is a fantastic solution) and thanks.
