### ISSUE TITLE
is it possible to prevent db-file getting corrupted by race condition if multiple nodejs processes read/write to the same file?

### ISSUE THREAD

**Issue by kaizhu256** [louischatriot/nedb#384]
is it possible to prevent db-file getting corrupted by race condition if multiple nodejs processes read/write to the same file? i added attachment for the corrupted file

using browser version of nedb @ v1.6.0 hacked to be isomorphic and can run on both node and browser:

```
$ npm start
> /Users/kaizhu/src/swagger-lite/lib.nedb.js:99
!function(t){if("function"==typeof bootstrap)bootstrap("nedb",t);else if("object"==typeof exports)module.exports=t();else if("function"==typeof define&&define.amd)define(t);else if("undefined"!=typeof ses){if(!ses.ok())return;ses.makeNedb=t}else"undefined"!=typeof window?window.Nedb=t():global.Nedb=t()}(function(){var t;return function(t,e,n){function r(n,o){if(!e[n]){if(!t[n]){var a="function"==typeof require&&require;if(!o&&a)return a(n,!0);if(i)return i(n,!0);throw new Error("Cannot find module '"+n+"'")}var u=e[n]={exports:{}};t[n][0].call(u.exports,function(e){var i=t[n][1][e];return r(i?i:e)},u,u.exports)}return e[n].exports}for(var i="function"==typeof require&&require,o=0;o<n.length;o++)r(n[o]);return r}({1:[function(t,e,n){function r(t,e){if(t.indexOf)return t.indexOf(e);for(var n=0;n<t.length;n++)if(e===t[n])return n;return-1}var i=t("__browserify_process");i.EventEmitter||(i.EventEmitter=function(){});var o=n.EventEmitter=i.EventEmitter,a="function"==

Error: Can't insert key 100, it violates the unique constraint
    at r.insert (/Users/kaizhu/src/swagger-lite/lib.nedb.js:100:17735)
    at n.insert (/Users/kaizhu/src/swagger-lite/lib.nedb.js:100:18150)
    at i.insert (/Users/kaizhu/src/swagger-lite/lib.nedb.js:99:20773)
    at i.insertMultipleDocs (/Users/kaizhu/src/swagger-lite/lib.nedb.js:99:20872)
    at i.insert (/Users/kaizhu/src/swagger-lite/lib.nedb.js:99:20503)
    at i.reset (/Users/kaizhu/src/swagger-lite/lib.nedb.js:99:20419)
    at /Users/kaizhu/src/swagger-lite/lib.nedb.js:99:13626
    at Array.forEach (native)
    at n.resetIndexes (/Users/kaizhu/src/swagger-lite/lib.nedb.js:99:13593)
    at /Users/kaizhu/src/swagger-lite/lib.nedb.js:100:3180
process exited with code 1
```

[Pet.txt](https://github.com/louischatriot/nedb/files/145094/Pet.txt)

**Comment by lukasbestle** [comment]
Kind of a duplicate of #353. Conclusion: This can't be supported by NeDB or any other embedded database.

**Comment by kaizhu256** [comment]
ok, closing
