### ISSUE TITLE
RangeError: Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by james-mckinnon** [louischatriot/nedb#405]
I'm aware of #177 and saw that particular issue was fixed almost two years ago. However, I have noticed that over the past month I have had the same error 4 times.

```
RangeError: Maximum call stack size exceeded at /Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:24:16 at /Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/lib/executor.js:36:39 at Datastore._insert (/Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/lib/datastore.js:350:12) at /Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/lib/executor.js:40:13 at Object.q.process (/Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:731:21) at next (/Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:728:27) at /Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:24:16 at /Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/lib/executor.js:36:39 at Datastore._insert (/Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/lib/datastore.js:350:12) at /Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/lib/executor.js:40:13 at Object.q.process (/Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:731:21) at next (/Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:728:27) at /Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:24:16 at /Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/lib/executor.js:36:39 at /Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/lib/datastore.js:355:12 at Persistence.persistNewState (/Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/lib/persistence.js:192:35) at Datastore._insert (/Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/lib/datastore.js:353:20) at /Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/lib/executor.js:40:13 at Object.q.process (/Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:731:21) at next (/Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:728:27) at /Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:24:16 at /Applications/HTTPSChecker.app/Contents/Resources/app.asar/node_modules/nedb/lib/executor.js:36:39
```

The application I am developing uses neDB to store Mixed Content issues it finds on a site until it can be displayed in a report. I abstracted the database functions into its own module and the code is below: 

```javascript
var Datastore = require('nedb'),
	csv = require('to-csv'),
	issuesDB = new Datastore();

/* Make sure the database is clean */
issuesDB.remove({}, { multi: true });

module.exports = {
	wipe: function () {
		issuesDB.remove({}, { multi: true });
	},

	insert: function (realID, section, protocol, path, issue, html) {
		issuesDB.insert({ _real_id: realID, section: section, protocol: protocol, path: path, issue: issue, html: html });
	},

	find: function (callback) {
		issuesDB.find({}).sort({ _real_id: 1 }).exec(function (err, docs) {
			callback(docs);
		});
	},

	csv: function (callback) {
		issuesDB.find({}).sort({_real_id: 1}).exec(function (err, docs) {

			if (err) {
				callback(new Error('CSV: Failed to get records from Datastore'));
			}

			docs.map(function (row) {
				delete row.url_id;
				delete row.issues;
				delete row._id;
				delete row._real_id;
				var issue = row.html.replace(/[\r\n]/g, ' ').split(': ', 2);
				row.issue = issue[0];
				row.html = issue[1];
				row.section = row.section.replace('activeResources', 'Active Resource').replace('passiveResources', 'Passive Resource');
			});

			callback(csv(docs));
		});
	}
};
```

I'm currently using version 1.8.0 of nedb.

**Comment by louischatriot** [comment]
Please follow the bug reporting guidelines and resubmit, I'll then reopen this issue.

**Comment by louischatriot** [comment]
(guidelines are in the readme)

**Comment by james-mckinnon** [comment]
Apologies, the reason why I didn't follow the bug reporting guidelines is because I'm not sure where or why it is happening. We're mainly submitting it now to find out if you or anyone else has seen this recently, hoping that with more information, we can track down the issue.

**Comment by louischatriot** [comment]
Understood, but the way you submitted makes it nearly impossible to help you, hence my comment :)

What I can say is that it was observed elsewhere but it was always a problem in the user's code so I assume that's the same this time. That's usually a recursion issue, which can be solved using a control flow library like `async` (https://github.com/caolan/async). Following the bug reportiung guidelines mentioned above is usually a pretty efficient way to pinpoint and eliminate the issue. In your case it's tricky since it's hard to replicate, the key is large datasets: try to run your code on a very large dataset and at some point you should be able to replicat'e it 100% of the time. Then trim down while keeping the error and you should be able to pinpoint where the issue is.
