### ISSUE TITLE
escaping field names?

### ISSUE THREAD

**Issue by chovy** [louischatriot/nedb#477]
How should I properly escape field names? 

I'm just inserting raw json and I get this error sometimes:

    Error: Field names cannot contain a .
        at checkKey (/home/username/tmp/spider/node_modules/nedb/lib/model.js:36:11)
        at /home/username/tmp/spider/node_modules/nedb/lib/model.js:54:7
        at Array.forEach (native)
        at checkObject (/home/username/tmp/spider/node_modules/nedb/lib/model.js:53:22)
        at /home/username/tmp/spider/node_modules/nedb/lib/model.js:48:7
        at Array.forEach (native)
        at checkObject (/home/username/tmp/spider/node_modules/nedb/lib/model.js:47:9)
        at /home/username/tmp/spider/node_modules/nedb/lib/model.js:55:7
        at Array.forEach (native)
        at checkObject (/home/username/tmp/spider/node_modules/nedb/lib/model.js:53:22)

**Comment by jampy** [comment]
Field names can't contain a dot since it is a character that has special meaning in MongoDB/nedb queries (it's the field separator). The same applies for the `$` sign.

You can't simply insert any unfiltered JSON, you must make sure that no field names contain that sign.

**Comment by chovy** [comment]
do you recommend I replace `.` with `_` and do you know of any easy way to do this?
I don't know what the fields are ahead of time.

**Comment by jampy** [comment]
> do you recommend I replace . with _ 

that would be one possibility, yes

> and do you know of any easy way to do this?

You could recursively scan the object and replace those properties. However, that could lead to collisions (what if a "foo.bar" and a "foo_bar" already exist in your source document..) and honestly it doesn't feel "right" to just store documents with unknown structure - but I don't know what you're trying to do.

**Comment by chovy** [comment]
well i'm just starting this project. and i don't know how many different keys I'll have with a `.` in them. so far i've found quite a few different ones. they all seem to have `foo.utf8` where `foo` can be anything.

I don't know an easy way to change that to `fooUtf8`
