### ISSUE TITLE
Cannot read property '_id' of undefined at Datastore.prepareDocumentForInsertion

### ISSUE THREAD

**Issue by andreesteve** [louischatriot/nedb#532]
nedb@1.8.0

Not quite sure what the repro is (somewhat big stack on top of NeDB), but there is a promise that fails (possibly not returned to caller?), that causes node to complain:
```
(node:6320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '_id' of undefined
(node:6320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

and here is the call stack

```
unhandledRejection TypeError: Cannot read property '_id' of undefined
    at Datastore.prepareDocumentForInsertion (/home/andre/projects/greeny/services/node_modules/nedb/lib/datastore.js:385:21)
    at Datastore._insert (/home/andre/projects/greeny/services/node_modules/nedb/lib/datastore.js:348:24)
    at /home/andre/projects/greeny/services/node_modules/nedb/lib/executor.js:40:13
    at Object.process (/home/andre/projects/greeny/services/node_modules/async/lib/async.js:731:21)
    at next (/home/andre/projects/greeny/services/node_modules/async/lib/async.js:728:27)
    at Immediate._onImmediate (/home/andre/projects/greeny/services/node_modules/async/lib/async.js:24:16)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```
It might not be NeDB's fault (e.g. caller passed some bogus parameters) but should at least null checks be in place and an explicit exception thrown instead?

I'm trying to get a repro with only NeDB - I'll update this issue if I am able to.

**Comment by bdfoster** [comment]
I'd check downstream first. Looks like someone isn't handling rejected
promises correctly anyway.
