### ISSUE TITLE
Getting the full stack trace for an error

### ISSUE THREAD

**Issue by tomavitan** [louischatriot/nedb#562]
The stack trace is not going all the way to my code that triggered it. I got too many calls to nedb, it'll be hard to track it myself.

1. What am I missing?
2. How would you recommend handling such errors? It uses the general "Error" object, so I would have to look for a certain error message, which seems to me not a good practice.

`[error] UncaughtException: Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss
      at Persistence.treatRawData (X/node_modules/nedb/lib/persistence.js:242:11)
      at /X/node_modules/nedb/lib/persistence.js:281:38
      at tryToString (fs.js:449:3)
      at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)`

For the record - I know what the exception means.

**Comment by tomavitan** [comment]
Found my answer - using npm's "stackup" I could get the full stack trace for the async calls. Not recommended for production use.
