### ISSUE TITLE
Cannot read Property 'multi' of undefined

### ISSUE THREAD

**Issue by digimbyte** [louischatriot/nedb#592]
came across this bug today, probably when options weren't declared
`ERROR: G:\Discord\*****\node_modules\nedb\lib\datastore.js:568
  multi = options.multi !== undefined ? options.multi : false;
                  ^

TypeError: Cannot read property 'multi' of undefined
    at Datastore._update (G:\Discord\*****\node_modules\nedb\lib\datastore.js:568:19)
    at G:\Discord\*****\node_modules\nedb\lib\executor.js:40:13
    at Object.process (G:\Discord\*****\node_modules\async\lib\async.js:731:21)
    at next (G:\Discord\*****\node_modules\async\lib\async.js:728:27)
    at Immediate.<anonymous> (G:\Discord\*****\node_modules\async\lib\async.js:24:16)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)`

**Comment by digimbyte** [comment]
This was caused by incorrect variable's being sent in the wrong order
Would like to see some better error handling than an exit with exit code -1
